### ISSUE TITLE
redis配置报错

### ISSUE THREAD

**Issue by westudiodev** [slimkit/plus#390]
修改storage/configure/plus.yml:
```
database:
  ...
  redis:
    client: predis
    default:
      host: xxxxxxx
      port: 6379     
      password: xxxx
      database: 0
cache:
  default: redis
  stores:
    redis:
      driver: redis
      connection: default
```

报错：
Connection refused [tcp://127.0.0.1:6379]
<img width="1247" alt="screen shot 2018-09-24 at 17 28 36" src="https://user-images.githubusercontent.com/33219803/45945240-6f61ce00-c01f-11e8-9bd1-250144d17d9b.png">
